version: "3"

services:
  web:
    build:
      context: ./web/
      args:
        - VITE_API_ENDPOINT=http://localhost:3000/v1
    ports:
      - "5173:5173"

  express:
    build:
      context: ./express/
    ports:
      - "3000:3000"
    env_file:
      - ./express/.env
