download_model:
	wget https://cdn-129.anonfiles.com/X161JdUdyb/aa91efc6-1675008306/clf_nb.joblib
	wget https://cdn-107.anonfiles.com/Za6eJeUfye/b7e22042-1675008308/clf_svc.joblib
	wget https://cdn-143.anonfiles.com/O3V5J9Ucy3/7b8c6cc3-1675010233/clf_rf.joblib
